### ISSUE TITLE
Failing test scenarios

### ISSUE THREAD

**Issue by mehulkar** [DockYard/ember-cli-custom-assertions#61]
3 of the ember-try scenarios are failing after #55 merge (looks like tests didn't run there). Opening an issue to track:

```
ember-default-with-jquery
embroider-safe
embroider-optimized
```

### ember-defeault-with-jquery

Seems to be failing with:

```
Setting the `jquery-integration` optional feature flag to `true` was deprecated in Ember 3.x and removed in Ember 4.0.0. You must add the `@ember/optional-features` addon and set this feature to `false`.

For more information, see the deprecation guide: https://deprecations.emberjs.com/v3.x/#toc_optional-feature-jquery-integration
```

I tried adding this dependency into the ember try scenario, but it didn't seem to work (package was installed, but same failure message). It might make most sense to just drop this scenario. 

### embroider scenarios

Not sure what to do about these!

**Comment by mehulkar** [comment]
cc @miguelcobain in case you have ideas!

**Comment by mehulkar** [comment]
Realized after talking with @jleja that the Embroider scenarios were introduced in #55, so disabling them or adding `allowedToFail: true` is a good way forward.

**Comment by jleja** [comment]
Liking @mehulkar's solution to allow the Embroider scenarios to fail, which keeps the status visible until ultimately resolved.  

`ember-default-with-jquery` failure is due to the "default" version being 4.x, which requires you to use the `@ember/optional-features` addon, whose configuration lives in `/config/optional-features.json`.  I don't immediately see a way to support that kind of configuration option within `ember-try`, so I think we can pin that to a 3.x version and consider either removing it in the future or seeing if it can be configured differently.

Looked at `@ember/jquery` to see how they were handling it, but it looks like the last good run of `ember-release-with-jquery` was back in July.  All other PRs bomb on `ember-beta` and skip this check.  So I think pinning to 3.28 should suffice for now.

**Comment by jleja** [comment]
Using the command on the jquery test `command: ember test feature:enable jquery-integrations` and including `@ember/optional-features` package in the scenario's `devDependencies` did the trick.  🎉
